// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using libDatos;

#nullable disable

namespace libDatos.Migrations
{
    [DbContext(typeof(ContextoEscuela))]
    [Migration("20220815222632_datosCalificaciones")]
    partial class datosCalificaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("libDatos.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoId"), 1L, 1);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroControl")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SemestreActual")
                        .HasColumnType("int");

                    b.HasKey("AlumnoId");

                    b.HasIndex("CarreraId");

                    b.ToTable("Alumnos", "dbo");

                    b.HasData(
                        new
                        {
                            AlumnoId = 1,
                            ApellidoMaterno = "HERNANDEZ",
                            ApellidoPaterno = "HERNANDEZ",
                            CarreraId = 3,
                            Estatus = 1,
                            Nombres = "MARCOS JESUS",
                            NumeroControl = "8001001",
                            SemestreActual = 1
                        },
                        new
                        {
                            AlumnoId = 2,
                            ApellidoMaterno = "GARCIA",
                            ApellidoPaterno = "PEREZ",
                            CarreraId = 1,
                            Estatus = 0,
                            Nombres = "PEDRO",
                            NumeroControl = "8001002",
                            SemestreActual = 0
                        });
                });

            modelBuilder.Entity("libDatos.Calificacion", b =>
                {
                    b.Property<int>("CalificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalificacionId"), 1L, 1);

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CalificacionId");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CursoId")
                        .IsUnique();

                    b.ToTable("Calificaciones", "dbo");

                    b.HasData(
                        new
                        {
                            CalificacionId = 1,
                            AlumnoId = 1,
                            CursoId = 1,
                            Nombre = "FINAL",
                            Valor = 5.0m
                        },
                        new
                        {
                            CalificacionId = 2,
                            AlumnoId = 1,
                            CursoId = 2,
                            Nombre = "FINAL",
                            Valor = 9.5m
                        });
                });

            modelBuilder.Entity("libDatos.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarreraId"), 1L, 1);

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SemestreFinal")
                        .HasColumnType("int");

                    b.Property<int>("SemestreInicial")
                        .HasColumnType("int");

                    b.HasKey("CarreraId");

                    b.ToTable("Carreras", "dbo");

                    b.HasData(
                        new
                        {
                            CarreraId = 1,
                            Activa = true,
                            NombreCarrera = "SIN CARRERA",
                            Plan = "",
                            SemestreFinal = 0,
                            SemestreInicial = 0
                        },
                        new
                        {
                            CarreraId = 2,
                            Activa = true,
                            NombreCarrera = "TRONCO COMUN ADMINISTRATIVO",
                            Plan = "2018",
                            SemestreFinal = 3,
                            SemestreInicial = 1
                        },
                        new
                        {
                            CarreraId = 3,
                            Activa = true,
                            NombreCarrera = "INGENIERIA EN SISTEMAS COMPUTACIONALES",
                            Plan = "2018",
                            SemestreFinal = 9,
                            SemestreInicial = 1
                        });
                });

            modelBuilder.Entity("libDatos.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"), 1L, 1);

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Cursos", "dbo");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            MateriaId = 3,
                            Nombre = "INTR-01-2022",
                            PeriodoId = 1
                        },
                        new
                        {
                            CursoId = 2,
                            MateriaId = 4,
                            Nombre = "MATE-01-2022",
                            PeriodoId = 1
                        });
                });

            modelBuilder.Entity("libDatos.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"), 1L, 1);

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaDependeId")
                        .HasColumnType("int");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("MateriaId");

                    b.HasIndex("CarreraId");

                    b.ToTable("Materias", "dbo");

                    b.HasData(
                        new
                        {
                            MateriaId = 1,
                            Activa = true,
                            CarreraId = 2,
                            MateriaDependeId = 0,
                            NombreMateria = "CONTABILIDAD I",
                            Semestre = 1
                        },
                        new
                        {
                            MateriaId = 2,
                            Activa = true,
                            CarreraId = 2,
                            MateriaDependeId = 0,
                            NombreMateria = "ADMINISTRACIÓN DE EMPRESAS I",
                            Semestre = 1
                        },
                        new
                        {
                            MateriaId = 3,
                            Activa = true,
                            CarreraId = 3,
                            MateriaDependeId = 0,
                            NombreMateria = "INTRODUCCIÓN A LA PROGRAMACIÓN",
                            Semestre = 1
                        },
                        new
                        {
                            MateriaId = 4,
                            Activa = true,
                            CarreraId = 3,
                            MateriaDependeId = 0,
                            NombreMateria = "MATEMATICAS DISCRETAS",
                            Semestre = 1
                        },
                        new
                        {
                            MateriaId = 5,
                            Activa = true,
                            CarreraId = 3,
                            MateriaDependeId = 3,
                            NombreMateria = "PROGRAMACION I",
                            Semestre = 2
                        },
                        new
                        {
                            MateriaId = 6,
                            Activa = true,
                            CarreraId = 3,
                            MateriaDependeId = 0,
                            NombreMateria = "ESTRUCTURA DE DATOS",
                            Semestre = 2
                        });
                });

            modelBuilder.Entity("libDatos.Periodo", b =>
                {
                    b.Property<int>("PeriodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodoId"), 1L, 1);

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("PeriodoId");

                    b.ToTable("Periodos", "dbo");

                    b.HasData(
                        new
                        {
                            PeriodoId = 1,
                            Anio = 2022,
                            Nombre = "01-2022",
                            Semestre = 1
                        });
                });

            modelBuilder.Entity("libDatos.Alumno", b =>
                {
                    b.HasOne("libDatos.Carrera", "oCarrera")
                        .WithMany("Alumnos")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("oCarrera");
                });

            modelBuilder.Entity("libDatos.Calificacion", b =>
                {
                    b.HasOne("libDatos.Alumno", "oAlumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("libDatos.Curso", "oCurso")
                        .WithOne()
                        .HasForeignKey("libDatos.Calificacion", "CursoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("oAlumno");

                    b.Navigation("oCurso");
                });

            modelBuilder.Entity("libDatos.Curso", b =>
                {
                    b.HasOne("libDatos.Materia", "oMateria")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("libDatos.Periodo", "oPeriodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("oMateria");

                    b.Navigation("oPeriodo");
                });

            modelBuilder.Entity("libDatos.Materia", b =>
                {
                    b.HasOne("libDatos.Carrera", "oCarrera")
                        .WithMany("Materias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("oCarrera");
                });

            modelBuilder.Entity("libDatos.Carrera", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
