//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        public int MateriaId { get; set; }
        public string NombreMateria { get; set; }
        public bool Activa { get; set; }
        public int CarreraId { get; set; }
    
        public virtual Carreras Carreras { get; set; }
    }
}
